services:
  slurmfrontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        image: noaagsl/slurm-frontend:latest
        shm_size: '4g'
        hostname: slurmfrontend
        user: admin
        volumes:
                - shared-vol:/home/admin
                - ufs-data:/opt/ufs-data
        ports:
                - 8888:8888
  slurmmaster:
        build:
          context: ./master
          dockerfile: Dockerfile
        image: noaagsl/slurm-master:latest
        shm_size: '4g'
        hostname: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_CPUS_ON_NODE=2
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurmnode1:
        build:
          context: ./node
          dockerfile: Dockerfile
        image: noaagsl/slurm-node:latest
        shm_size: '4g'
        hostname: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin
                - ufs-data:/opt/ufs-data
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=2
        links:
                - slurmmaster
  slurmnode2:
        build:
          context: ./node
          dockerfile: Dockerfile
        image: noaagsl/slurm-node:latest
        shm_size: '4g'
        hostname: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin
                - ufs-data:/opt/ufs-data
        environment:
                - SLURM_NODENAME=slurmnode2
                - SLURM_CPUS_ON_NODE=2
        links:
                - slurmmaster
  slurmnode3:
        build:
          context: ./node
          dockerfile: Dockerfile
        image: noaagsl/slurm-node:latest
        shm_size: '4g'
        hostname: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin
                - ufs-data:/opt/ufs-data
        environment:
                - SLURM_NODENAME=slurmnode3
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurmmaster
volumes:
        shared-vol:
        ufs-data:
          driver: local
          driver_opts:
            o: bind
            type: none
            device: /home/ubuntu/ufs-data
